version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/public
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php
      - db
  php:
    container_name: php
    build: .docker
    restart: always
    env_file:
      - .env
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
  composer:
    container_name: composer
    image: composer
    volumes:
      - .:/app
    command: install
  db:
    container_name: postgres
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
